development:
  secret_key_base: 90282e5758602f638e69fce658a047cb44e1ace0714d1d518be04805d9dae14c4545d41782c3e1adfa0ab6c49194b0345f7c11200244e7c144bdb56407dec87c
  app_domain: localhost:5000
  redis_url: redis://127.0.0.1:6379/
  sendgrid_username: <%= ENV["SENDGRID_USERNAME"] %>
  sendgrid_password: <%= ENV["SENDGRID_PASSWORD"] %>
  default_mail_sender: walter@getwalter.io

test:
  secret_key_base: ed7ae218939eee4685c1d2919555fdd55636e72328fda26e4b2142f0254e2d1fad19a8734ad3b2993c1827587555e73c66e5ae863d00dd4154d8d2c6908ec5b3
  app_domain: localhost:5000
  redis_url: redis://127.0.0.1:6379/
  sendgrid_username: <%= ENV["SENDGRID_USERNAME"] %>
  sendgrid_password: <%= ENV["SENDGRID_PASSWORD"] %>
  default_mail_sender: walter@getwalter.io

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  app_domain: <%= ENV["APP_DOMAIN"] %>
  redis_url: <%= ENV["REDIS_URL"] %>
  sendgrid_username: <%= ENV["SENDGRID_USERNAME"] %>
  sendgrid_password: <%= ENV["SENDGRID_PASSWORD"] %>
  default_mail_sender: <%= ENV["DEFAULT_MAIL_SENDER"] %>
  mixpanel_token: <%= ENV["MIXPANEL_TOKEN"] %>
